  CREATE TABLE "BICYCLES" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"BICYCLE_ID" VARCHAR2(50), 
	"BRAND" VARCHAR2(50), 
	"MODEL" VARCHAR2(50), 
	"CATEGORY" VARCHAR2(50), 
	"CONDITION" VARCHAR2(50), 
	"FRAME_SIZE" VARCHAR2(50), 
	"SELLING_PRICE" NUMBER, 
	"MIN_DOWN_PAYMENT" NUMBER, 
	"INSTALLMENT_PLAN" VARCHAR2(50), 
	"STATUS" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(4000), 
	"CUSTOMER_ID" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UC_BICYCLE_ID" UNIQUE ("BICYCLE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"PHONE_NUMBER" VARCHAR2(20), 
	"ADDRESS" VARCHAR2(255), 
	"EMAIL" VARCHAR2(100), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EBA_PROJECTS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"STATUS_ID" NUMBER, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"PROJECT_LEAD" VARCHAR2(255), 
	"BUDGET" NUMBER, 
	"COMPLETED_DATE" DATE, 
	"CREATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "EBA_PROJECTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EBA_PROJECTS_UK" UNIQUE ("NAME")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EBA_PROJECT_COMMENTS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"COMMENT_TEXT" VARCHAR2(4000) NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "EBA_PROJECT_COMMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EBA_PROJECT_MILESTONES" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"DUE_DATE" DATE NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "EBA_PROJECT_MILESTONES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EBA_PROJECT_STATUS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CODE" VARCHAR2(15) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255) NOT NULL ENABLE, 
	"DISPLAY_ORDER" NUMBER NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "EBA_PROJECT_USERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EBA_PROJECT_STATUS_UK" UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EBA_PROJECT_TASKS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"MILESTONE_ID" NUMBER, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"ASSIGNEE" VARCHAR2(255), 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE NOT NULL ENABLE, 
	"COST" NUMBER, 
	"IS_COMPLETE_YN" VARCHAR2(1), 
	"CREATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "EBA_PROJECT_TASKS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EBA_PROJECT_TASKS_UK" UNIQUE ("PROJECT_ID", "NAME")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EBA_PROJECT_TASK_LINKS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"TASK_ID" NUMBER NOT NULL ENABLE, 
	"LINK_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"URL" VARCHAR2(255), 
	"APPLICATION_ID" NUMBER, 
	"APPLICATION_PAGE" NUMBER, 
	"DESCRIPTION" VARCHAR2(4000), 
	"CREATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "EBA_PROJECT_TASK_LINKS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EBA_PROJECT_TSK_LINK_LTY_CH" CHECK ( link_type in ('URL','Application')) ENABLE
   ) ;

  CREATE TABLE "EBA_PROJECT_TASK_TODOS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"TASK_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"ASSIGNEE" VARCHAR2(255), 
	"IS_COMPLETE_YN" VARCHAR2(1), 
	"CREATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "EBA_PROJECT_TASK_TODOS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PAYMENTS" 
   (	"PAYMENT_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"BICYCLE_ID" VARCHAR2(50), 
	"CUSTOMER_ID" NUMBER, 
	"AMOUNT_PAID" NUMBER, 
	"PAYMENT_DATE" DATE DEFAULT SYSDATE, 
	"PAYMENT_METHOD" VARCHAR2(50), 
	"REMARKS" VARCHAR2(255), 
	 PRIMARY KEY ("PAYMENT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "EBA_PROJECTS" ADD CONSTRAINT "EBA_PROJECT_STATUS_FK" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "EBA_PROJECT_STATUS" ("ID") ON DELETE SET NULL ENABLE;

  CREATE INDEX "EBA_PROJECTS_STATUS_IDX" ON "EBA_PROJECTS" ("STATUS_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "EBA_PROJECTS_BIU" 
    before insert or update on eba_projects
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/
ALTER TRIGGER "EBA_PROJECTS_BIU" ENABLE;

  ALTER TABLE "EBA_PROJECT_COMMENTS" ADD CONSTRAINT "EBA_PROJECT_COMMENT_PROJ_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "EBA_PROJECTS" ("ID") ON DELETE CASCADE ENABLE;

  CREATE INDEX "EBA_PROJECT_COMMENT_PRJ_IDX" ON "EBA_PROJECT_COMMENTS" ("PROJECT_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "EBA_PROJECT_COMMENTS_BIU" 
    before insert or update on eba_project_comments
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/
ALTER TRIGGER "EBA_PROJECT_COMMENTS_BIU" ENABLE;

  ALTER TABLE "EBA_PROJECT_MILESTONES" ADD CONSTRAINT "EBA_PROJECT_MSTONE_PROJ_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "EBA_PROJECTS" ("ID") ON DELETE CASCADE ENABLE;

  CREATE INDEX "EBA_PROJECT_MSTONE_PROJ_IDX" ON "EBA_PROJECT_MILESTONES" ("PROJECT_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "EBA_PROJECT_MILESTONES_BIU" 
    before insert or update on eba_project_milestones
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/
ALTER TRIGGER "EBA_PROJECT_MILESTONES_BIU" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "EBA_PROJECT_STATUS_BIU" 
before insert or update on eba_project_status
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.code       := upper(:new.code);
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/
ALTER TRIGGER "EBA_PROJECT_STATUS_BIU" ENABLE;

  ALTER TABLE "EBA_PROJECT_TASKS" ADD CONSTRAINT "EBA_PROJECT_TASK_MSTONE_FK" FOREIGN KEY ("MILESTONE_ID")
	  REFERENCES "EBA_PROJECT_MILESTONES" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "EBA_PROJECT_TASKS" ADD CONSTRAINT "EBA_PROJECT_TASK_PROJ_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "EBA_PROJECTS" ("ID") ON DELETE CASCADE ENABLE;

  CREATE INDEX "EBA_PROJECT_TASK_PROJ_IDX" ON "EBA_PROJECT_TASKS" ("PROJECT_ID") 
  ;

  CREATE INDEX "EBA_PROJECT_TASK_MSTONE_IDX" ON "EBA_PROJECT_TASKS" ("MILESTONE_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "EBA_PROJECT_TASKS_BIU" 
    before insert or update on eba_project_tasks
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/
ALTER TRIGGER "EBA_PROJECT_TASKS_BIU" ENABLE;

  ALTER TABLE "EBA_PROJECT_TASK_LINKS" ADD CONSTRAINT "EBA_PROJECT_TSK_LINK_PRJ_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "EBA_PROJECTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "EBA_PROJECT_TASK_LINKS" ADD CONSTRAINT "EBA_PROJECT_TSK_LINK_TSK_FK" FOREIGN KEY ("TASK_ID")
	  REFERENCES "EBA_PROJECT_TASKS" ("ID") ON DELETE CASCADE ENABLE;

  CREATE INDEX "EBA_PROJECT_TSK_LINK_TK_IDX" ON "EBA_PROJECT_TASK_LINKS" ("TASK_ID") 
  ;

  CREATE INDEX "EBA_PROJECT_TSK_LINK_PR_IDX" ON "EBA_PROJECT_TASK_LINKS" ("PROJECT_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "EBA_PROJECT_TASK_LINKS_BIU" 
    before insert or update on eba_project_task_links
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/
ALTER TRIGGER "EBA_PROJECT_TASK_LINKS_BIU" ENABLE;

  ALTER TABLE "EBA_PROJECT_TASK_TODOS" ADD CONSTRAINT "EBA_PROJECT_TSK_TODO_TSK_FK" FOREIGN KEY ("TASK_ID")
	  REFERENCES "EBA_PROJECT_TASKS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "EBA_PROJECT_TASK_TODOS" ADD CONSTRAINT "EBA_PROJ_TASK_TODO_PROJ_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "EBA_PROJECTS" ("ID") ON DELETE CASCADE ENABLE;

  CREATE INDEX "EBA_PROJECT_TSK_TODO_TK_IDX" ON "EBA_PROJECT_TASK_TODOS" ("TASK_ID") 
  ;

  CREATE INDEX "EBA_PROJECT_TSK_TODO_PR_IDX" ON "EBA_PROJECT_TASK_TODOS" ("PROJECT_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "EBA_PROJECT_TASK_TODOS_BIU" 
    before insert or update on eba_project_task_todos
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/
ALTER TRIGGER "EBA_PROJECT_TASK_TODOS_BIU" ENABLE;

  ALTER TABLE "PAYMENTS" ADD CONSTRAINT "FK_PAY_BICYCLE" FOREIGN KEY ("BICYCLE_ID")
	  REFERENCES "BICYCLES" ("BICYCLE_ID") ENABLE;
  ALTER TABLE "PAYMENTS" ADD CONSTRAINT "FK_PAY_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMERS" ("CUSTOMER_ID") ENABLE;






































































































create or replace trigger eba_projects_biu
    before insert or update on eba_projects
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/
create or replace trigger eba_project_comments_biu
    before insert or update on eba_project_comments
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/
create or replace trigger eba_project_milestones_biu
    before insert or update on eba_project_milestones
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/
create or replace trigger eba_project_status_biu
before insert or update on eba_project_status
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.code       := upper(:new.code);
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/
create or replace trigger eba_project_tasks_biu
    before insert or update on eba_project_tasks
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/
create or replace trigger eba_project_task_links_biu
    before insert or update on eba_project_task_links
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/
create or replace trigger eba_project_task_todos_biu
    before insert or update on eba_project_task_todos
    for each row
begin
    if inserting then
        :new.created    := current_timestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    end if;
    :new.updated    := current_timestamp;
    :new.updated_by := nvl(wwv_flow.g_user,user);
end;
/


























